#!/bin/bash

MPLBACKEND=Agg python -c "import matplotlib.pyplot"  # Build font cache.

# Enable Jupyter extension(s):
jupyter serverextension enable --py nbgitpuller --sys-prefix

# Create symlink to caproto-repeater so that libca finds a caRepeater executable.
ln -s caproto-repeater /srv/conda/bin/caRepeater
