#!/bin/bash

pip install -e ./content/bluesky-tutorial-utils

MPLBACKEND=Agg python -c "import matplotlib.pyplot"  # Build font cache.

# Create symlink to caproto-repeater so that libca finds a caRepeater executable.
ln -s caproto-repeater `python -c "import os, sys; print(os.path.dirname(sys.executable))"`/caRepeater
